version: '3'

services:
  db:
    image: postgres:14.6-alpine3.17
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./data/postgres/14/database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:6.2-alpine3.17
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data/redis/database_data:/data

  greenlight-v3:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v3
    container_name: greenlight-v3
    restart: unless-stopped
    env_file: sample.env
    ports:
      - 127.0.0.1:5000:3000
    
    volumes:
      - ./data/greenlight-v3/storage:/usr/src/app/storage
    depends_on:
      - db
      - redis
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: name@exemple.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    links:
      - db       